# Generated by Django 5.1.6 on 2025-03-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_loginotpmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('course_photo', models.ImageField(upload_to='uploads/')),
                ('tutor_name', models.CharField(max_length=50)),
                ('tutor_email', models.EmailField(max_length=254)),
                ('tutor_contact', models.IntegerField(max_length=10)),
            ],
        ),
    ]
