# Generated by Django 5.1.6 on 2025-03-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_coursesdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesdata',
            name='tutor_contact',
            field=models.CharField(max_length=10),
        ),
    ]
