# Generated by Django 5.1.6 on 2025-03-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_alter_coursesdata_tutor_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_name', models.CharField(max_length=100)),
                ('tutor_email', models.EmailField(max_length=254)),
                ('tutor_contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='coursesdata',
            name='course_photo',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
