# Generated by Django 5.1.6 on 2025-03-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tutordata_alter_coursesdata_course_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='coursesdata',
            name='course_photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
