# Generated by Django 5.1.6 on 2025-03-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_course_studentdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='courses',
            field=models.ManyToManyField(to='Admin.coursesdata'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.ManyToManyField(to='Admin.coursesdata'),
        ),
    ]
