# Generated by Django 5.1.6 on 2025-03-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_remove_course_course_name_alter_studentdata_courses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
