# Generated by Django 5.1.6 on 2025-03-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_customuser_password_alter_studentdata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='courses',
            new_name='course_name',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdata',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
