# Generated by Django 5.1.6 on 2025-03-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_rename_courses_studentdata_course_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='username',
            new_name='student_name',
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='EnrollStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('joined_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_name', models.ManyToManyField(to='Admin.coursesdata')),
            ],
        ),
    ]
