# Generated by Django 5.1.6 on 2025-03-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_rename_username_studentdata_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
