# Generated by Django 5.1.6 on 2025-03-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_alter_studentdata_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorData',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='profile',
            field=models.ImageField(default='default_profile', upload_to='uploads/'),
        ),
    ]
