# Generated by Django 5.1.6 on 2025-03-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_delete_tutordata_studentdata_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='profile',
        ),
    ]
